import { CheckCircle, Scales, Sparkle, ArrowRight } from '@phosphor-icons/react'
import { Card } from '../../../components/ui/Card'
import { Badge } from '../../../components/ui/Badge'
import { Button } from '../../../components/ui/Button'
import { formatCurrency } from '../../../utils/formatters'
import { useSettlementStore } from '../../settlements/store/useSettlementStore'

/**
 * Compact financial snapshot for the trip overview.
 * Gives immediate visibility into whether the trip is all settled or has
 * remaining settlement payments, without calculating balances in React.
 *
 * Distinguishes:
 * 1. Financial settlement requirement generated by the engine
 * 2. Remaining unpaid settlement transactions
 *
 * @param {{
 *   trip: Object,
 *   financialSummary: {
 *     settlements: Array<Object>,
 *     totalSpent: number
 *   },
 *   expensesCount: number,
 *   onAddExpense?: () => void
 * }} props
 */
export function TripFinancialSnapshot({
  trip,
  financialSummary,
  expensesCount,
  onAddExpense,
}) {
  const currency = trip.currency || 'INR'
  const payments = useSettlementStore((s) => s.payments)
  const isSettlementPaid = useSettlementStore((s) => s.isSettlementPaid)

  const settlements = financialSummary?.settlements || []
  const pendingSettlements = settlements.filter((s) => payments && !isSettlementPaid(trip.id, s))
  const pendingCount = pendingSettlements.length

  // Case 1: No expenses recorded yet
  if (expensesCount === 0) {
    return (
      <Card className="p-5 sm:p-6 bg-amber-50/70 border-2 border-dashed border-zinc-300 rounded-3xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3.5">
            <div className="w-10 h-10 rounded-2xl bg-white border-2 border-zinc-900 text-amber-600 flex items-center justify-center font-black shrink-0 shadow-playful-sm">
              <Sparkle className="w-5 h-5" weight="fill" />
            </div>
            <div>
              <h3 className="text-base font-black text-zinc-900 tracking-tight">
                Financial Status
              </h3>
              <p className="text-xs sm:text-sm text-zinc-600 font-medium">
                No money drama yet. Log group expenses and TripSplit will calculate who owes whom.
              </p>
            </div>
          </div>

          {onAddExpense && (
            <Button
              variant="primary"
              size="sm"
              onClick={onAddExpense}
              className="self-start sm:self-auto shrink-0"
            >
              Add First Expense
            </Button>
          )}
        </div>
      </Card>
    )
  }

  // Case 2: All Settled (expenses exist, but settlements array is empty OR all generated settlements are marked paid)
  if (settlements.length === 0 || pendingCount === 0) {
    return (
      <Card className="p-5 sm:p-6 bg-teal-50/80 border-2 border-zinc-900 shadow-playful rounded-3xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3.5">
            <div className="w-11 h-11 rounded-2xl bg-teal-200 border-2 border-zinc-900 text-teal-950 flex items-center justify-center shrink-0 shadow-playful-sm">
              <CheckCircle className="w-6 h-6" weight="bold" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base sm:text-lg font-black text-zinc-900 tracking-tight">
                  All Settled
                </h3>
                <Badge variant="teal" className="text-[10px] font-black">
                  All square
                </Badge>
              </div>
              <p className="text-xs sm:text-sm text-zinc-700 font-medium mt-0.5">
                Everyone is square. No payments are currently needed.
              </p>
            </div>
          </div>

          <Button
            to={`/trips/${trip.id}/settlement`}
            variant="outline"
            size="sm"
            icon={Scales}
            className="self-start sm:self-auto shrink-0"
          >
            View Settle Up
          </Button>
        </div>
      </Card>
    )
  }

  // Case 3: Money to Settle (active pending settlements remain)
  const remainingSettlementMoney = pendingSettlements.reduce((acc, curr) => acc + curr.amount, 0)

  return (
    <Card className="p-5 sm:p-6 bg-gradient-to-r from-amber-50 to-orange-50/60 border-2 border-zinc-900 shadow-playful rounded-3xl">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-start sm:items-center gap-3.5">
          <div className="w-11 h-11 rounded-2xl bg-amber-300 border-2 border-zinc-900 text-zinc-950 flex items-center justify-center shrink-0 shadow-playful-sm">
            <Scales className="w-6 h-6" weight="bold" />
          </div>
          <div>
            <div className="flex flex-wrap items-center gap-2">
              <h3 className="text-base sm:text-lg font-black text-zinc-900 tracking-tight">
                Money to Settle
              </h3>
              <Badge variant="yellow" className="text-[10px] font-black">
                {pendingCount} {pendingCount === 1 ? 'payment' : 'payments'} remaining
              </Badge>
            </div>
            <p className="text-xs sm:text-sm text-zinc-700 font-medium mt-0.5">
              <span className="font-extrabold text-zinc-950">
                {formatCurrency(remainingSettlementMoney, currency)}
              </span>{' '}
              still needs to move between people to square up.
            </p>
          </div>
        </div>

        <Button
          to={`/trips/${trip.id}/settlement`}
          variant="primary"
          size="sm"
          icon={ArrowRight}
          className="self-start md:self-auto shrink-0"
        >
          Settle Up
        </Button>
      </div>
    </Card>
  )
}
